spring:
  datasource:
    url: jdbc:sqlite:stoofdb.sqlite
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 1
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
